name: Validacao de Seguranca da Sprint 4

on:
  push:
    branches: [ main ]

jobs:
  # Job 1: Provar que a ferramenta ENCONTRA o erro no código antigo
  analise-codigo-vulneravel:
    runs-on: ubuntu-latest
    # Este job PODE falhar, e está tudo bem.
    continue-on-error: true
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar e rodar o Semgrep
        run: |
          pip install semgrep
          # Rodamos o Semgrep esperando um erro (--error) no arquivo vulnerável
          semgrep --config=auto --error ./app-vulneravel.js

  # Job 2: Provar que o erro NÃO EXISTE MAIS no código novo
  analise-codigo-corrigido:
    runs-on: ubuntu-latest
    # Este job precisa do Job 1 para terminar, mesmo que ele falhe
    needs: analise-codigo-vulneravel
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar e rodar o Semgrep
        run: |
          pip install semgrep
          # Rodamos o Semgrep no arquivo corrigido, aqui ele deve passar
          semgrep --config=auto ./app-corrigido.js
