name: Validacao de Seguranca da Sprint 4

on:
  push:
    branches: [ main ]

jobs:
  analise-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar Semgrep no código VULNERÁVEL (esperamos que falhe)
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true  # ADICIONE ESTA LINHA
        with:
          args: --error --config=auto ./app-vulneravel.js

      - name: Rodar Semgrep no código CORRIGIDO (esperamos que passe)
        uses: returntocorp/semgrep-action@v1
        with:
          args: --config=auto ./app-corrigido.js
